Updated zipalign script Framework files don't like getting zipaligned

diff --git a/02zipalign b/02zipalign
--- a/02zipalign
+++ b/02zipalign
@@ -45,24 +45,24 @@ echo "Starting Automatic ZipAlign $( date +"%m-%d-%Y %H:%M:%S" )" | tee -a $LOG_
 	zipalign -c 4 $apk1;
 	ZIPCHECK1=$?;
 	if [ $ZIPCHECK1 -eq 1 ]; then
-		echo ZipAligning $(busybox basename $apk1)  | tee -a $LOG_FILE;
-		zipalign -f 4 $apk1 /cache/$(busybox basename $apk1);
-			if [ -e /cache/$(busybox basename $apk1) ]; then
-				cp -f -p /cache/$(busybox basename $apk1) $apk1  | tee -a $LOG_FILE;
-				rm /cache/$(busybox basename $apk1);
-			else
-				echo ZipAligning $(busybox basename $apk1) Failed  | tee -a $LOG_FILE;
-			fi;
-	else
-		echo ZipAlign already completed on $apk1  | tee -a $LOG_FILE;
-	fi;
-       done;
+		# echo ZipAligning $(busybox basename $apk1)  | tee -a $LOG_FILE;
+		# zipalign -f 4 $apk1 /cache/$(busybox basename $apk1);
+			# if [ -e /cache/$(busybox basename $apk1) ]; then
+				# cp -f -p /cache/$(busybox basename $apk1) $apk1  | tee -a $LOG_FILE;
+				# rm /cache/$(busybox basename $apk1);
+			# else
+				# echo ZipAligning $(busybox basename $apk1) Failed  | tee -a $LOG_FILE;
+			# fi;
+	# else
+		# echo ZipAlign already completed on $apk1  | tee -a $LOG_FILE;
+	# fi;
+       # done;
 	   
-	echo "Attempting to zipalign system apps";
-	for apk1 in /system/app/*.apk ; do
-	zipalign -c 4 $apk1;
-	ZIPCHECK1=$?;
-	if [ $ZIPCHECK1 -eq 1 ]; then
+	# echo "Attempting to zipalign system apps";
+	# for apk1 in /system/app/*.apk ; do
+	# zipalign -c 4 $apk1;
+	# ZIPCHECK1=$?;
+	# if [ $ZIPCHECK1 -eq 1 ]; then
 		echo ZipAligning $(busybox basename $apk1)  | tee -a $LOG_FILE;
 		zipalign -f 4 $apk1 /cache/$(busybox basename $apk1);
 			if [ -e /cache/$(busybox basename $apk1) ]; then
